config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get 'training', to: 'training#home', as: :training
  get 'training/io', to: 'training#io', as: :io
  get 'training/elara', to: 'training#elara', as: :elara
  get 'training/studios', to: 'training#studios', as: :studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'about', to: 'about#home', as: :about
  get 'about/press', to: 'about#press', as: :press
  get 'about/careers', to: 'about#careers', as: :career
  get 'blog', to: 'blog#home', as: :blog
  get 'contact', to: 'contact#home', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def home
  end

  def press
  end

  def careers
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def home
  end

  def show
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def training
  end

  def about
  end

  def blog
  end

  def contact
  end
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController
  def home
  end

  def io
  end

  def elara
  end

  def studios
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/careers.html.erb
<div class="careers-section">
  <div class="careers-title">
    <%= image_tag 'about-icon-left', class: "careers-icon" %>
    <h3>INTERSTELLAR TEAMWORK</h3>
  </div>

  <div class="careers-desc">
  <h5>We are on a mission to transform learning at scale through Virtual Reality</h5>
    <%= image_tag 'about-icon-left', class: "careers-icon" %>
  </div>

  <div class="careers-tag">
    <p>It may seem like a mammoth task, but the team at MOONHUB isn’t fazed by it. In fact, they are all up for a challenge or two. <br> Together we work hard, we bounce ideas off each other, and we have lots of snacks.</p>
  </div>

  <div class="career-benefits">
    <h3>BENEFITS OF WORKING WITH US</h3>
    <div class="benefits">
      <div class="row justify-content-around mb-5">
        <div class="col-3 benefit">
          <%= image_tag "benefit-1" %>
          <h5> Flexible working</h5>
        </div>
        <div class="col-3 benefit">
          <%= image_tag "benefit-2"%>
          <h5> Innovative workspace</h5>
        </div>
        <div class="col-3 benefit">
          <%= image_tag "benefit-3" %>
          <h5> Learning & Growth</h5>
        </div>
      </div>
      <div class="row justify-content-around mb-5">
        <div class="col-3 benefit">
          <%= image_tag "benefit-4" %>
          <h5> Equity options</h5>
        </div>
        <div class="col-3 benefit">
          <%= image_tag "benefit-5" %>
          <h5> Private healthcare insurance</h5>
        </div>
        <div class="col-3 benefit">
          <%= image_tag "benefit-6" %>
          <h5> Enhanced parental leave</h5>
        </div>
      </div>
    </div>
  </div>


  <div class="career-cta">
    <h3>WANT TO VENTURE WITH US?</h3>
    <p>We currently have no more space in our rocket ship, but we are always expanding! <br> Send a copy of your CV to <span id="moonhub-email"> moonbase@themoonhub.com </span> and we will notify you when <br> a suitable role becomes available!</p>
  </div>
</div>

app/views/about/press.html.erb
<div class="press-section">
  <div class="press-title">
    <%= image_tag 'about-icon-left', class: "press-icon" %>
    <h3>OUR MOONLIT EXPERIENCES</h3>
  </div>

  <div class="press-desc">
    <p>Explore the articles and blogs where we've left our cosmic footprints.</p>
    <%= image_tag 'about-icon-left', class: "press-icon" %>
  </div>


  <div class="cards-container">
    <div class="row justify-content-around mb-5">
      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-1" %>
          <div class="press-blog-infos">
            <div>
              <h2>How we harnessed the power ot VR to support health workers</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path do %>
        <div class="press-blog">
          <%= image_tag "press-2" %>
          <div class="press-blog-infos">
            <div>
              <h2>Welcome to our new MH-07 office space</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-3" %>
          <div class="press-blog-infos">
            <div>
              <h2>Supporting workplace wellbeing through Virtual Reality</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="row justify-content-around mb-5">
      <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-4" %>
            <div class="press-blog-infos">
              <div>
                <h2>We are upgrading our headsets</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-5" %>
          <div class="press-blog-infos">
            <div>
              <h2>Changing corporate cultures</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path do %>
        <div class="press-blog">
          <%= image_tag "press-6" %>
          <div class="press-blog-infos">
            <div>
              <h2>The future of VR</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>


    <div class="row justify-content-around mb-5">
      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-3" %>
          <div class="press-blog-infos">
            <div>
              <h2>Supporting workplace wellbeing through Virtual Reality</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-1" %>
          <div class="press-blog-infos">
            <div>
              <h2>How we harnessed the power ot VR to support health workers</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-2" %>
          <div class="press-blog-infos">
            <div>
              <h2>Welcome to our new MH-07 office space</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>


  </div>

  <div class="load-more">
    <button>LOAD MORE</button>

      <div class="cards-container d-none">
      <div class="row justify-content-around mb-5">
        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-1" %>
            <div class="press-blog-infos">
              <div>
                <h2>How we harnessed the power ot VR to support health workers</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path do %>
          <div class="press-blog">
            <%= image_tag "press-2" %>
            <div class="press-blog-infos">
              <div>
                <h2>Welcome to our new MH-07 office space</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-3" %>
            <div class="press-blog-infos">
              <div>
                <h2>Supporting workplace wellbeing through Virtual Reality</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>

      <div class="row justify-content-around mb-5">
        <div class="col-3">
          <%= link_to root_path  do %>
            <div class="press-blog">
              <%= image_tag "press-4" %>
              <div class="press-blog-infos">
                <div>
                  <h2>We are upgrading our headsets</h2>
                  <p>16 June 2023</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-5" %>
            <div class="press-blog-infos">
              <div>
                <h2>Changing corporate cultures</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path do %>
          <div class="press-blog">
            <%= image_tag "press-6" %>
            <div class="press-blog-infos">
              <div>
                <h2>The future of VR</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>


      <div class="row justify-content-around mb-5">
        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-3" %>
            <div class="press-blog-infos">
              <div>
                <h2>Supporting workplace wellbeing through Virtual Reality</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-1" %>
            <div class="press-blog-infos">
              <div>
                <h2>How we harnessed the power ot VR to support health workers</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>

        <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-2" %>
            <div class="press-blog-infos">
              <div>
                <h2>Welcome to our new MH-07 office space</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>


    </div>

  </div>
</div>

app/views/blog/home.html.erb
<div class="press-section">
  <div class="press-title">
    <%= image_tag 'about-icon-left', class: "press-icon" %>
    <h3 id="blog-title">EXPLORE OUR BLOGOSPHERE</h3>
  </div>

  <div class="press-desc">
    <p>Explore the articles and blogs where we've left our cosmic footprints.</p>
    <%= image_tag 'about-icon-left', class: "press-icon" %>
  </div>


  <div class="cards-container">
    <div class="row justify-content-around mb-5">
      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-1" %>
          <div class="press-blog-infos">
            <div>
              <h2>How we harnessed the power ot VR to support health workers</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path do %>
        <div class="press-blog">
          <%= image_tag "press-2" %>
          <div class="press-blog-infos">
            <div>
              <h2>Welcome to our new MH-07 office space</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-3" %>
          <div class="press-blog-infos">
            <div>
              <h2>Supporting workplace wellbeing through Virtual Reality</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="row justify-content-around mb-5">
      <div class="col-3">
        <%= link_to root_path  do %>
          <div class="press-blog">
            <%= image_tag "press-4" %>
            <div class="press-blog-infos">
              <div>
                <h2>We are upgrading our headsets</h2>
                <p>16 June 2023</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-5" %>
          <div class="press-blog-infos">
            <div>
              <h2>Changing corporate cultures</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path do %>
        <div class="press-blog">
          <%= image_tag "press-6" %>
          <div class="press-blog-infos">
            <div>
              <h2>The future of VR</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>


    <div class="row justify-content-around mb-5">
      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-3" %>
          <div class="press-blog-infos">
            <div>
              <h2>Supporting workplace wellbeing through Virtual Reality</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-1" %>
          <div class="press-blog-infos">
            <div>
              <h2>How we harnessed the power ot VR to support health workers</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>

      <div class="col-3">
      <%= link_to root_path  do %>
        <div class="press-blog">
          <%= image_tag "press-2" %>
          <div class="press-blog-infos">
            <div>
              <h2>Welcome to our new MH-07 office space</h2>
              <p>16 June 2023</p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>


  </div>
</div>

app/views/contact/home.html.erb
<div class="contact-section">
  <div class="contact-container">
        <div class="row justify-content-between">
          <div class="col-5">
            <h3>BOOK A MEETING WITH OUR SALES TEAM</h3>
            <p>Unravel new training possibilities. <br> Set up a meeting with our Sales team.</p>
          </div>
          <div class="col-5">
            <%= image_tag "calendly" %>
          </div>
        </div>
        <div class="row justify-content-between">
          <div class="col-5">
            <h3>...OR, LEAVE A MESSAGE WITH YOUR <br> QUERY, AND WE WILL BE IN TOUCH</h3>
            <p>Unravel new training possibilities. <br> Set up a meeting with our Sales team.</p>
          </div>
          <div class="col-5">
            <form action="">
              <div class="form-group mb-4">
                <label for="fullname">Full name</label>
                <input class="form-control"type="text" name="fullname">
              </div>
              <div class="form-group mb-4">
                <label for="email">Email address</label>
                <input class="form-control"type="email" name="email">
              </div>
              <div class="form-group mb-4">
                <label for="company">Company name (optional)</label>
                <input class="form-control"type="text" name="company">
              </div>
              <div class="form-group mb-4">
                <label for="message">Add your message</label>
                <textarea class="form-control" name="message" id="" cols="30" rows="10">
                </textarea>
              </div>
              <input type="submit" class="log-in" id="submit">
            </form>
          </div>
        </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moonhub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="page-container">
  <div class="content-wrap">
  <%= render "shared/navbar" %>
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="f-container">
    <div class="f-logo">
      <%= image_tag "MH-logotype-light" %>
      <p> &copy All right reserved The MOONHUB 2023</p>
    </div>
    <div class="link-list">
      <ul>
        <li>Home</li>
        <li>About</li>
        <li>Careers</li>
        <li>Press</li>
      </ul>
      <ul>
        <li>Training</li>
        <li>IO</li>
        <li>Elara</li>
        <li>Studios</li>
      </ul>
      <ul>
        <li>Resources</li>
        <li>Shop</li>
        <li>Customer Support</li>
        <li>Contact</li>
      </ul>
    </div>
    <div class="f-icons">
      <i class="fa-brands fa-twitter" style="color: #2A2730;"></i>
      <i class="fa-brands fa-square-instagram" style="color: #2A2730;"></i>
      <i class="fa-brands fa-linkedin" style="color: #2A2730;"></i>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if params[:controller].upcase == 'PAGES' || params[:controller].upcase == 'TRAINING' %>
  <div class="navbar container">
    <%= image_tag "moonhub-logo" %>
    <%= link_to "HOME", root_path, class: "#{'active' if params[:action].upcase == 'HOME' && params[:controller].upcase == 'PAGES'}"%>
    <div class="t-dd">
      <%= link_to "TRAINING", training_path, class: "#{'active' if params[:controller].upcase == 'TRAINING'}"%>
        <div class="dropdown-menu training-trigger">
          <div class="spacer"></div>
              <div class="the-dropdown d-dark">
                <%= link_to io_path do %>
                  <div>
                    <h3>IO</h3>
                  </div>
                <% end %>
                <%= link_to elara_path do %>
                  <div>
                    <h3> ELARA </h3>
                  </div>
                <% end %>
                <%= link_to studios_path do %>
                  <div>
                    <h3>STUDIOS</h3>
                  </div>
                <% end %>
              </div>
          </div>
      </div>
    <div class="ah">
      <%= link_to "ABOUT", about_path, class: "#{'active' if params[:action].upcase == 'ABOUT'}" %>
        <div class="dropdown-menu about-trigger">
          <div class="spacer"></div>
            <div class="the-dropdown d-dark">
              <%= link_to press_path do %>
                <div>
                  <h3>PRESS</h3>
                </div>
              <% end %>
              <%= link_to career_path do %>
                <div>
                  <h3> CAREERS </h3>
                </div>
              <% end %>
            </div>
          </div>
      </div>
    <%= link_to "BLOG", blog_path, class:  "#{'active' if params[:action].upcase == 'BLOG'}" %>
    <%= link_to "CONTACT", contact_path, class: "#{'active' if params[:action].upcase == 'CONTACT'}" %>
    <div class="d-flex">
      <%= link_to "SHOP", root_path, class: "shop#{'active' if params[:action].upcase == 'SHOP'}" %>
      <%= link_to "LOG IN", root_path, class: "log-in #{'active' if params[:action].upcase == 'LOG IN'}" %>
    </div>
  </div>
<% else %>
  <div class="navbar container">
    <%= image_tag "moonhub-logo-dark" %>
    <%= link_to "HOME", root_path, class: "dark "%>
    <div class="t-dd">
      <%= link_to "TRAINING", training_path, class: "dark " + "#{'active' if params[:action].upcase == 'TRAINING'}"%>
       <div class="dropdown-menu training-trigger">
          <div class="spacer"></div>
          <div class="the-dropdown d-light">
            <%= link_to io_path do %>
              <div>
                <h3>IO</h3>
              </div>
            <% end %>
            <%= link_to elara_path do %>
              <div>
                <h3> ELARA </h3>
              </div>
            <% end %>
            <%= link_to studios_path do %>
              <div>
                <h3>STUDIOS</h3>
              </div>
            <% end %>
          </div>
      </div>
    </div>
    <div class="ah">
    <%= link_to "ABOUT", about_path, class: "dark dropdown " + "#{'active' if params[:controller].upcase == 'ABOUT'}" %>
    <div class="dropdown-menu about-trigger">
      <div class="spacer"></div>
          <div class="the-dropdown d-light">
            <%= link_to press_path do %>
              <div>
                <h3>PRESS</h3>
              </div>
            <% end %>
            <%= link_to career_path do %>
              <div>
                <h3> CAREERS </h3>
              </div>
            <% end %>
          </div>
      </div>
    </div>
    <%= link_to "BLOG", blog_path, class:  "dark " + "#{'active' if params[:action].upcase == 'BLOG'}" %>
    <%= link_to "CONTACT", contact_path, class: "dark " + "#{'active' if params[:action].upcase == 'CONTACT'}" %>
    <div class="d-flex">
      <%= link_to "SHOP", root_path, class: "shop#{'active' if params[:action].upcase == 'SHOP'}" %>
      <%= link_to "LOG IN", root_path, class: "log-in #{'active' if params[:action].upcase == 'LOG IN'}" %>
    </div>
  </div>
<% end %>

app/views/training/home.html.erb
<div class="landing-title">
  <h6>THE TWO SIDES TO MOONHUB</h6>

  <div class="landing-info">
    <div class="library">
        <%= image_tag 'Moondarkside' %>
        <h5> LIBRARY </h5>
        <p> Developed by leading L&D professionals. <br><br>
          The MOONHUB Library is our industry-standard, readily available VR training solutions.<br><br><br>
          Accredited by CPD.</p>
    </div>

    <div class="studios">
      <%= image_tag 'Moonlightside' %>
      <h5> STUDIOS </h5>
      <p>Co-curated with you, for you. <br><br>
        MOONHUB Studios is your on-demand production house which translates your learning objectives into a bespoke VR training experience. <br><br>
        The power of MOONHUB, your way.</p>
    </div>
  </div>
  <div class="scroll-cta">
    <p>Explore our training offering</p>
    <%= image_tag 'scroll-down', class: "scroll-icon" %>
  </div>
</div>

<div class="page-dividers">
  <%= image_tag 'gradient-left' %>
  <%= image_tag 'gradient-right' %>
</div>

<div class="products">
  <div class="products-intro">
    <h6>MOONHUB LIBRARY</h6>
    <p>Corporate training is changing. MOONHUB unlocks your employees’ potential with our state-of-the-art virtual reality training solutions</p>
  </div>

  <div class="product">
    <div class="p-headings">
      <h5>IO</h5>
      <h6>THE WORKPLACE ESSENTIAL'S TOOLKIT</h6>
    </div>
    <div class="p-info">
      <%= image_tag 'io', class: 'product-pic'%>
      <div class="p-description">
        <p>Expertly curated for all teams, our essentials suite provides industry-standard best practices, certified by CPD. <br><br>
          More than just a training, IO is a transformational experience for your team, where the very essence of each topic comes alive in an engaging and immersive virtual environment, from Diversity and Inclusion to Health and Safety and Well-being.<br><br>
          With IO, training that is usually just a box to tick transforms into a powerful tool for growth and success.</p>
      </div>
    </div>
    <div class="product-cta">
      <%= link_to "DISCOVER IO", io_path, class: 'cta-button' %>
    </div>
  </div>
  <div class="product">
    <div class="p-headings">
      <h5>ELARA</h5>
      <h6>A MASTERCLASS IN HEALTHCARE</h6>
    </div>
    <div class="p-info">
      <%= image_tag 'elara', class: 'product-pic'%>
      <div class="p-description">
        <p>ELARA offers an interactive journey into the world of dementia. Learners will be able to step into the shoes of those afflicted by the condition, gaining key insights into their experiences, emotions, and needs.<br><br>
          Studied to strengthen soft skills to enhance empathy and deliver superior care.<br><br>
          ELARA is a holistic, low-risk, highly immersive new health and social care workforce approach.</p>
      </div>
    </div>
    <div class="product-cta">
      <%= link_to "DISCOVER ELARA", elara_path, class: 'cta-button' %>
    </div>
  </div>
  <div class="product">
    <div class="p-headings">
      <h5>MOONHUB STUDIOS</h5>
      <h6>TURN YOUR TRAINING DREAMS INTO VIRTUAL REALITY. POWERED BY MOONHUB.</h6>
    </div>
    <div class="p-info">
      <%= image_tag 'moonhub-studios', class: 'product-pic'%>
      <div class="p-description">
        <p>Co-curated with you, for you.<br><br>
          MOONHUB Studios is your on-demand production house which translates your learning objectives into a bespoke VR training experience.<br><br>
          Our innovative program goes beyond the one-size-fits-all approach by offering a truly bespoke training solution, where you can design training content that aligns perfectly with your requirements.<br><br>
          The power of MOONHUB, your way.</p>
      </div>
    </div>
    <div class="product-cta">
      <%= link_to "DISCOVER STUDIOS", studios_path, class: 'cta-button' %>
    </div>
  </div>
</div>

<div class="page-dividers-2">
  <%= image_tag 'gradient-left' %>
  <%= image_tag 'gradient-right' %>
</div>

<div class="training-3">

  <div class="heading">
    <h5>YOUR EXPERIENCE DOESN'T END IN THE HEADSET</h5>
  </div>

  <div class="patent">
    <h6>OUR PATENT</h6>
    <p id="patent-desc">Our Spot-and-Jot patented VR technology utilises a 5 layered cognitive scoring system to record <br>learners' performances in ways never done before. <br><br>
    Learners are tested in gamified training scenarios in five key metrics to equip them with the <br> necessary skills for their roles.</p>
    <%= image_tag 'patent-diagram' %>
    <p id="patent-cta">Learn more about our scoring system</p>
    <%= link_to "GET IN TOUCH", "#", class: "cta-git" %>
  </div>

  <div class="heading">
    <h5> YOUR ANALYTICS </h5>
  </div>

  <div class="analytics">
    <div class="analytics-stats">
      <div class="analytic-stat">
        <%= image_tag 'a-stat-1' %>
        <p>View, assess and reflect <br> on training scores.</p>
      </div>
      <div class="analytic-stat">
        <%= image_tag 'a-stat-2' %>
        <p>Verify the training experience with official <br> MOONHUB certificates, accredited by CPD.</p>
      </div>
      <div class="analytic-stat">
        <%= image_tag 'a-stat-3' %>
        <p>Download additional information packs</p>
      </div>
    </div>
    <div class="analytics-img">
      <%= image_tag 'laptop-image' %>
    </div>
  </div>

  <div class="heading">
    <h5> WHAT OUR USERS SAY </h5>
  </div>

  <div class="review-carousel">
    <div class="review">
      <p>“Our partnership with MOONHUB has rejuvenated our learning experience, creating a more efficient and enjoyable training platform for our organisation. MOONHUB has changed the negative stigma around mandatory training into a positive, more engaging event.”​</p>
      <h6>ISS</h6>
    </div>

    <div class="review">
      <p>"Our collaboration with MOONHUB has been credited by winning “Outstanding Training Initiative” at the Outstanding Security Performance Awards (OSPAs), in February 2022."</p>
      <h6>Corps Security</h6>
    </div>

     <%# <div class="review">
      <p>"Our collaboration with MOONHUB has been credited by winning “Outstanding Training Initiative” at the Outstanding Security Performance Awards (OSPAs), in February 2022."</p>
      <h6>Corps Security</h6>
    </div> %>
  </div>

  <div class="final-cta">
    <h5> ARE YOU READY TO LAUNCH YOUR TRAINING TO NEW HEIGHTS? </h5>
    <%= link_to "GET IN TOUCH", "#", class: "cta-git" %>
  </div>

</div>

app/views/training/studios.html.erb
<h1>Training#studios</h1>
<p>Find me in app/views/training/studios.html.erb</p>